### ISSUE TITLE
Get rid of all the static stuff

### ISSUE THREAD

**Issue by tfrommen** [reisraff/phulp#11]
I don't see any valid reason for `static` stuff (except for the `Output` class, maybe). Is there any particular reason you chose this not consequently object-oriented approach?

I already refactored a local clone to work object-oriented.
If you're interested in that, I could redo this in a fork, and open a pull request.

Key changes:
- well, no `static` Phulp methods;
- constructor inject an `Output` object into Phulp;
- pass `$this` (i.e., the Phulp object) to each task callback;
- refactor `Watch`: don't pass in `$tasks` (which you don't even need), but a (new) Phulp callback. 

This way it is easier to write real unit test - which I'd be glad to help you with, BTW.

Another plus for testing would be using factories (for DistFile, Source and Watch) - but that's another story/issue.

**// EDIT:** This is how a `PhulpFile.php` could look like:
```php
$phulp->task('default', function ($phulp) {
    $phulp->src(['src/'], '/php$/')
        ->pipe($phulp->iterate(function ($distFile) {
            echo $distFile->getName() . PHP_EOL;
        }));
});
```

**Comment by reisraff** [comment]
Hey @tfrommen Im so happy to see you wanting to help the php community with this project.

Answering you, I used static methods because I wanted a way to write the PhulpFile.php like the gulpfile.js, and this was the most similar I got.

But I like this approach... feel free to fork and help us.

The unique thing I think is not good is injection unde Phulp.

**Comment by oliveiramiguel** [comment]
I was thinking about it some day ago and I did a draft using `builder` approach. Phulp class in this case just will care about tasks. 

I did this way, because for me is strange all those methods in Phulp class.

```php
Phulp\Phulp::task('default', function (Phulp\Builder $b) {
    $b->start(['clear'])
      ->src(['src/'], '/php$/', false)
      ->pipe(function() {
          'xxxxxx';
      });
});
```

**Comment by reisraff** [comment]
@oliveiramiguel I agree with you, but we need think that "everyone is used to with the gulpjs" and gulpjs haven't a `builder`, everything is `gulp`, I prefer a way that is easy to write the `PhulpFile` even having all those methods in the $phulp object.
