### ISSUE TITLE
Adding separate files

### ISSUE THREAD

**Issue by leon-mbs** [reisraff/phulp#40]
Sometimes  we  need to add files in a certain order. Therefore, it would be good to be able to add seperate files not only directives.

**Comment by reisraff** [comment]
Can you please give me a real example?

**Comment by leon-mbs** [comment]
I have tried  to  add  jquery.js , bootstrap.js and  a few  jquery plugins into one  bundle (ones  are  used  in my  framework so I wanted to simplify assests). It worked with gulp  but  I got errors when files were joined  with Phulp.  CSS classes  sometimes required  certain sequence too.

**Comment by reisraff** [comment]
What you talking about is the order of import like, the bootstrap.js has dependency of jquery.js... and it must be imported in this order also.

If is that, what you want is something like that: https://github.com/reisraff/phulp-angular-filesort

please, show me your gulp script, then may I can write some code similar for you.

**Comment by leon-mbs** [comment]
I see. The files  can be sorted.  I saw the plugin but I was  confused a litle with angular word.
 

 gulp.task('js', function() {
    return gulp.src([  
         'assets/js/jquery/jquery.js',  
        'assets/js/bootstrap.js',    
        'assets/js/jquery/jquery.form.js',  
        'assets/js/bootstrap3-typeahead.js'           
        ])
        .pipe(concat('zippy-bundle.min.js'))  
         .pipe(uglify()) 
        .pipe(gulp.dest('assets/js'));  
});

**Comment by reisraff** [comment]
With this script, and this file structure you can get what you want.

```
.
└── assets
    └── js
        ├── bootstrap
        │   └── bootstrap.js
        ├── bootstrap3-typeahead
        │   └── bootstrap3-typeahead.js
        ├── jquery
        │   └── jquery.js
        └── jquery-form
            └── jquery.form.js
```

```php
<?php

use Phulp\Output as out;

$phulp->task('run', function ($phulp) {
    $phulp->src(
        [
            'assets/js/jquery', // directory
            'assets/js/bootstrap', // directory
            'assets/js/jquery-form', // directory
            'assets/js/bootstrap3-typeahead', // directory
        ],
        '/js$/',
        false
    )->pipe($phulp->iterate(function ($distFile) {
        out::out($distFile->getName());
    }));
});

$phulp->task('default', function ($phulp) {
    $phulp->start(['run']);
});
```

**Comment by leon-mbs** [comment]
I will try.  Thanks a lot!
