### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by nsrosenqvist** [reisraff/phulp#49]
Error in console, angular undefined. Seems like you've missed including the script dependencies?

**Comment by nsrosenqvist** [comment]
@reisraff I only seem to be getting the issue in Firefox, works fine in Chrome. Does FF work for you?

**Comment by reisraff** [comment]
true

**Comment by itepifanio** [comment]
Working on it

**Comment by reisraff** [comment]
this commit https://github.com/reisraff/phulp/commit/cf8e5a337c2b1d90ba631ea33628bbdac2f60958 fix it
