### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by nsrosenqvist** [reisraff/phulp#50]
Hi! I've just started using phulp in the hope of removing node dependencies when building simple PHP projects. So glad I found this since it is exactly what I wanted for so long (especially paired with [Asset Packagist](https://asset-packagist.org/)). I've just published a bunch of plugins I've put together for a current project, several features commonly used for gulp plus one that makes it possible to pipe files to Assetic for preprocessing. Doing this I've noticed drastic performance differences between phulp and gulp and I believe it's mostly due to gulps parallelism and streaming paradigm.

After a bit of research, my suggestions for improving phulp is as follows (this is partially based on assumptions in the code base, I've looked through most of it but I may have missed something):
1. **Use globbing patterns as sources rather than a separately defined regex.** Many beginners have a really hard to put together proper regex patterns and the minimatch patterns gulp uses are a lot simpler to understand. This project gets us very close for the same globbing features (only need to add parantheses, e.g. `(jpg|png)`, to make it fully compatible): https://github.com/webmozart/glob

   The linked library has a glob matching feature (`Glob::match`) which could be used to exclude files from the source in case they are prefixed by an exclamation mark, e.g. '!**/.gitkeep'

2. **Implement threading and byte streams.** Gulp's strength and performance comes from its use of streams. Usually parallel programming is implemented in PHP with the pthreads extension but it can be done without extensions through the [amphp project](https://amphp.org/). Then the pipe implementation could be reworked to handle streams and tasks could be run in parallel. The pipes could then (either by inheritance or method definitions) handle streams, buffered files, or wait until all files are buffered to process them in one batch command (probably not recommended but perhaps sometimes wanted). This would also allow splitting streams as is a quite common practice with gulp when you have specific preprocessing rules for some files.

3. **Make watch event-based.** Using inotify it could be converted into listening for events rather than polling for changes in the filesystem. Since inotify is not usually packaged with default php installations we could check for the extension first and automatically select the poll-based approach whenever inotify is missing in the environment.

I might start looking at this when I find some time in case there would be interest in pursuing making phulp threaded? Would something like this be merged or is it not inline with the project's goals? I assume it would be since it's inspired by gulp, but would like confirmation first.

Thanks for a great project!

**Comment by nsrosenqvist** [comment]
@reisraff great! I might look at this in the next few weeks. Will probably finish my current project with the current version though before looking at this.

**Comment by reisraff** [comment]
https://github.com/reisraff/phulp/commit/38f530f2630e324670ed25638d15c61ab684c279

**Comment by reisraff** [comment]
I am gonna close this issue, and open another for enhance the glob feature adding the "!" behavior.

But for now, the only thing we will not implement is the inotify.
