### ISSUE TITLE
phulpfile.php~ -> "There are more than one Phulpfile present."

### ISSUE THREAD

**Issue by jaysee** [reisraff/phulp#52]
Hello,

When editing `phulpfile.php` Emacs create a temporary files named `phulpfile.php~` and phulp complains with message `There are more than one Phulpfile present.`, cleaning the temp file fix the problem, but it's anoying :)

Thanks

**Comment by reisraff** [comment]
https://github.com/reisraff/phulp/releases/tag/2.1.1
