### ISSUE TITLE
Keep a CHANGELOG

### ISSUE THREAD

**Issue by rogeriopradoj** [reisraff/phulp#7]
Hi, @reisraff , nice work on this project.

I suggest you take a look at http://keepachangelog.com/ .

See ya!

**Comment by reisraff** [comment]
Thank you for the advice.

https://github.com/reisraff/phulp/commit/a06db4dfe67f2bee3db8d3157259d92c126d9e9c

**Comment by rogeriopradoj** [comment]
:clap: :clap: :clap:
