### ISSUE TITLE
Write the unit tests

### ISSUE THREAD

**Issue by reisraff** [reisraff/phulp#8]

**Comment by reisraff** [comment]
@tfrommen can you write the tests? I'll bump the version after close this issue.

**Comment by tfrommen** [comment]
I can start with it, sure.

**Comment by tfrommen** [comment]
@reisraff any reason for using PHP 5.6, but PHPUnit 4.5.* (and not 4.8, for example)?

I guess it is okay for me to adapt `composer.json`, `phpunit.xml.dist` and the `test` directory, right?

**Comment by reisraff** [comment]
@tfrommen no, It was just copy and past, you can update the composer.json and phpunit.xml.dist.

About test directory I din't understand.

**Comment by tfrommen** [comment]
Okay then.

Regarding the `test` directory... When I write both and (**real**) unit and integration tests, I usually put them in separate folders. This leads to the unit tests being in, for example, `/test/unit/`, and the integration tests in `/test/integration/`.
